language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - python setup.py install

script:
  - python -m unittest discover -s tests/multitax/unit/ -v
  - python -m unittest discover -s tests/multitax/integration/ -v

notifications:
  email: false
