language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_install:
  - python -m pip install coverage

install:
  - python setup.py install

script:
  - python -m unittest discover -s tests/multitax/unit/ -v
  - python -m unittest discover -s tests/multitax/integration/ -v
  - coverage run --append -m unittest discover -s tests/ganon/unit/ -v;
  - coverage run --append -m unittest discover -s tests/ganon/integration/ -v;

notifications:
  email: false
